-- One row per successfully executed (user, key). The row is inserted as the FIRST statement of the
-- reservation transaction, so concurrent duplicates serialise on this primary key before touching
-- any seat. reservation_id is generated by the application up front; the FK is deferred so it is
-- checked at commit, after the reservation row exists in the same transaction.
CREATE TABLE idempotency_keys (
    user_id         text        NOT NULL,
    idem_key        text        NOT NULL CHECK (length(idem_key) BETWEEN 1 AND 128),
    request_hash    bytea       NOT NULL CHECK (octet_length(request_hash) = 32),
    show_id         uuid        NOT NULL REFERENCES shows (id),
    reservation_id  uuid        NOT NULL REFERENCES reservations (id) DEFERRABLE INITIALLY DEFERRED,
    response_status smallint,
    response_body   jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, idem_key)
);
